### ISSUE TITLE
Run local search on initial solutions

### ISSUE THREAD

**Issue by wouterkool** [PyVRP/PyVRP#156]
The original HGS implementation runs the local search on the initial solutions before inserting them into the population. We don't do this, and as a result, parents involved in the crossover are not locally optimal in the first phase of the algorithm, which may affect the crossover and local search runtime of the offspring. Should we test whether it is an improvement to educate the initial individuals before inserting them in the initial population?

**Comment by N-Wouda** [comment]
I only have Euro/NeurIPS results to back this up with, but at least on those instances there was no meaningful difference between starting with random individuals, or starting with a population of already-educated individuals. That's why we took it out. But I am not sure if that result generalises.

**Comment by wouterkool** [comment]
At least its helpful to know this was an informed decision :). I think it may be worth reconsidering, if not for performance perhaps also for consistency (i.e. making the population always contain locally optimally individuals).

**Comment by N-Wouda** [comment]
From the paper:
![image](https://user-images.githubusercontent.com/16272507/222096123-781d6f68-26ba-4923-bae0-d0d0b1ff2959.png)
This doesn't say everything, but just looking at the diversity on a GH1000 instance suggests that after, say, 200 iterations there isn't much difference compared to later iterations. At that point we've had a few purges, and those should be pretty good at weeding out really bad random solutions.

>I think it may be worth reconsidering, if not for performance perhaps also for consistency (i.e. making the population always contain locally optimally individuals).

How should we support this? It seems strange to me to have the Population know about or depend on the educator/local search, like in HGS-CVRP or -VRPTW. An alternative might be to require the population be seeded with a set of initial solutions constructed outside of the population. That'd also clean up a lot of the other dependencies the population has, so I was already in favour of this, but that would push more work to the user who then also has to think about seeding the population (instead of that happening by default).

**Comment by leonlan** [comment]
#168 introduced an `initial_solutions` argument to the GeneticAlgorithm. This way the user is now responsible for passing the desired initial solutions to the algorithm. The initial solutions are used again when restarting the population, but I don't think that's an issue since the other parts of the algorithm introduce randomness.

**Comment by N-Wouda** [comment]
> #168 introduced an `initial_solutions` argument to the GeneticAlgorithm. This way the user is now responsible for passing the desired initial solutions to the algorithm. The initial solutions are used again when restarting the population, but I don't think that's an issue since the other parts of the algorithm introduce randomness.

Since we pushed the initial solutions to userland, they can now also be held responsible for improving them through educate. I am closing this issue as a result: this is not something we are responsible for any longer.
