### ISSUE TITLE
Reduce coupling

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#157]
A lot of things depend on a lot of things right now. Sometimes that's unavoidable, but there are also definitely cases where it kind of grew together that way (e.g., we found a recent case in #152). This issue serves two goals:

1. Determine how each class and function depends on the other classes and functions;
2. Decide which of these are OK/desirable, and which of these we should try to get rid of.

**Comment by N-Wouda** [comment]
`Individual` stores a pointer to a `ProblemData` instance, but that is not actually needed: it's only passed to the constructor for initialisation (similarly to how `XorShift128` is used there). After that it's unnecessary.

**Comment by N-Wouda** [comment]
Similarly, `TimeWindowSegment` stores a pointer to the distance matrix. But that's only needed when it's merged with other TWS, and can be passed in at that point.

**Comment by N-Wouda** [comment]
#162 addresses the above-mentioned two cases. The following is a list of classes that depend on other classes. I do not consider cases where the dependency is transient (e.g., just a function argument but no state), but only those where an internal reference to an external object is kept within the class - the dependency has to be part of the _state_ of the class.

With that criterion, we have the following in `pyvrp`:

- GeneticAlgorithm: depends on ProblemData, PenaltyManager, XorShift128, Population, LocalSearch, GeneticAlgorithmParams
- Individual: depends on PenaltyManager
- Matrix: none
- PenaltyManager: none
- Population: depends on ProblemData, PenaltyManager, XorShift128, PopulationParams
- ProblemData: none
- Result: depends on Individual and Statistics
- Statistics: none
- SubPopulation: depends on PopulationParams, which is owned by Population
- TimeWindowSegment: none
- XorShift128: none

The `pyvrp.crossover` and `pyvrp.diversity` modules define only stateless functions. We might want to have a look at their function signatures at a later point in time as well.

In `pyvrp.educate`:

- All operators: ProblemData, PenaltyManager
- LocalSearch: ProblemData, PenaltyManager, XorShift128
- Node: ~ProblemData (why?)~ EDIT: removed in #162
- Route: ProblemData

And that's about it.

**Comment by wouterkool** [comment]
I am a big fan of improving this. Some additional thoughts:
* I think naming and decoupling of things also relates to the overal philosophy of PyVRP, I have made #164 for this.
* Regarding PenaltyManager, see #100 which will help decouple things. Major question is how to deal with the population if costs change due to changed penalties.
* Randomness: I think it would be helpful if we could explicitly pass around a `rng` object so it is clear which components are deterministic or not, and we can avoid components having random state. I have made https://github.com/N-Wouda/PyVRP/issues/163 to discuss how to handle randomness in general.

**Comment by leonlan** [comment]
#168 removed the `ProblemData`, `PenaltyManager` and `XorShift` members from Population. I have crossed them out in the list above.

**Comment by N-Wouda** [comment]
> In `pyvrp.educate`:
> 
> * All operators: ProblemData, PenaltyManager
> * LocalSearch: ProblemData, PenaltyManager, XorShift128
> * Node: Node, Route, ~ProblemData~
> * Route: ProblemData, Node

Most of these things have a necessary dependency on `ProblemData` because they need access to the problem characteristics to evaluate moves. I think that's expected and OK. Nodes and Routes depend on each other to indicate membership: nodes point to their route, and routes know about the nodes that are in them. We could perhaps simplify that further (I vaguely see a future where Nodes disappear altogether), but for now that makes sense to me and isn't very pressing.

The `XorShift128` RNG is used by `LocalSearch` to shuffle the operator and node/route order before searching. We can make that more explicit by passing the RNG in along with the individual.

Finally, we have the `PenaltyManager` dependency. We can probably remove that once it's gone from `Individual`.

**Comment by wouterkool** [comment]
I agree it is ok to rely on `ProblemData` as we can consider that constant in the local search. All other dependencies I'd prefer to have explicit where they are needed.

For the `rng` in `LocalSearch`, see #163, I think we could also set the random order from Python, or alternatively at least make the `shuffle` a separate function, taking the `rng` object that we can optionally call from Python (which would give more control to Python and make the `search` function itself deterministc).

Regarding loading and exporting an Individual from LocalSearch, couldn't we just bind those functions separately? We've discussed it before, it may not be faster but I think it's cleaner as you can scope any dependencies (such as PenaltyManager although that will be removed) needed for load/export to those functions rather than search/intensify.

**Comment by N-Wouda** [comment]
I think this issue is basically done with the removal of the RNG from the (C++) LS's state.
