### ISSUE TITLE
Prize collecting VRP?

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#180]
We currently support the CVRP and VRPTW. For a paper I am working on, I need some form of prize collecting: in my problem, we do not have to visit every client, but instead get to choose for each client if the value of visiting is worth the expensive in travel time/distance. 

I am not sure if PyVRP should support this directly, but opening an issue to track it costs nothing. I will work on prize collecting in a branch or fork first (can I fork my own repo? 😄). If it's easy we might consider merging those changes in, if not, perhaps not.

I will use this issue to comment on that progress a bit.

**Comment by leonlan** [comment]
I'm in favor of supporting as many VRP variants as possible, especially those that are relatively common in the VRP literature (prize-collecting included). 

We can think about how to make it work with PyVRP once you have some implementation. I think it then becomes much easier to see where things "break" and how it will affect the current variants and possible other variants :-).

**Comment by wouterkool** [comment]
I thought I replied already but apparently not! I think it would be great if we can support this and should not be that difficult! BTW, this was also implemented by Kleopatra and TeamSB during EURO Meets NeurIPS.

**Comment by libklein** [comment]
I am not sure if you'd want this to be part of the main repo as our implementation (Team Kleopatra) invalidates a major assumption of the HGS, specifically that individuals are always complete. Im not sure if some parts of PyVRP's codebase rely on this assumption (I could imagine that, e.g., SREX does) or planned components will. 

A different approach could be to put the decision of whether to serve a customer or not into the evaluation function. This is what Thibaut did in his paper on PC-VRPs: https://pubsonline.informs.org/doi/abs/10.1287/trsc.2015.0584. This is hard to do in a computationally efficient fashion and will likely require a rewrite of the concatenation procedure, but is what I'd recommend for your research. Feel free to reach out to me if you're interested in the concept.

**Comment by wouterkool** [comment]
@libklein thanks for your comment.

I quickly skimmed through Thibaut's paper and it is quite interesting as it keeps all customers assigned to a route, which means they can be 'reinserted' quickly when that becomes feasible. However I think the resource constrained shortest path does not play well with having both a distance and time window aspect. :(

For the time being, I think a simpler approach where we can just assign/unassign a node would make sense. My suggestion would be:
- for assign, I think we can use `Relocate` (`Exchange<1,0>`) which should check if the node is currently unassigned, meaning that the delta cost for route `U` should be computed as `-U->prize` (as we decrease cost by the prize) rather than based on distance/penalties.
- for unassign, I see two options:
  - a `LocalSearchOperator<Node>` that ignores `V` (bit wasteful as it will be checked for all neighbours)
  - a special local search operator operating on a single node?

This seems quite similar to @libklein's implementation [here](https://github.com/tumBAIS/euro-meets-neurips-2022/blob/main/pchgs/src/LocalSearch.cpp#L474), which also suggests we do the unassign (and possibly assign) seperately at the end, like moves involving an empty route.

I think the assumption that individuals are complete have rather few implications expect for some implimentation details, e.g. in SREX we can just disregard it (like we do for time windows) or skip inserting optional left-over customers.

I saw @N-Wouda already made a nice start, although I'm not sure if we should keep unassigned customers in a special route? I think we still need to treat them specially so I would suggest really unassigning them (using a seperate property or making `Node->route` optional).
