### ISSUE TITLE
Implement Subpopulation in Python

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#283]
`SubPopulation` is currently implemented in C++ because of performance reasons (see #120, #44). An earlier attempt at implementing this in Python (https://github.com/PyVRP/PyVRP/pull/88) was discontinued because it contained some bugs that we couldn't solve and we were time pressured for the submission deadline. However, the PR showed that we _can_ create a fast implementation of `SubPopulation` in Python using vectorization. I'll have an attempt at this in early August.

**Comment by N-Wouda** [comment]
I think [some of the tests here](https://github.com/PyVRP/PyVRP/blob/main/pyvrp/tests/test_SubPopulation.py) already implement a reasonably efficient vectorised biased fitness computation.

**Comment by wouterkool** [comment]
I think all of the complexity in my previous solution was to incrementally maintain the biased fitness... I think I did not try just computing it lazily when needed using the vectorized solution in the tests... which may or may not be acceptible.

I was also thinking that we could maybe just implement it differently/approximately without hurting performance, for example:
- just compute the diversity and/or ranks only when inserting the individual rather than updating them continuously
- or maybe update them only every x iterations / only when purging (which removes the need to track statistics incrementally for performance)

Thinking about this a little more there are two places where biased fitness is used:
- In the binary tournament parent selection. Here I would expect little difference if we use slightly different/outdated/approximated fitness values.
- In the purge. Since this is only every x iterations, it would be acceptible to recompute biased fitness here. However, the purge currently removes individuals 1 by 1 and recomputes the biased fitness for each. Maybe here we can remove more than 1 (or even all) individuals at once without hurting performance.
