### ISSUE TITLE
LNS support

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#307]
This does not really have a dedicated issue yet, although #182 is a part of LNS support. Similarly, the open PR #301 also touches on this.

I think we should work towards supporting operators for large neighbourhood search, perhaps in a `pyvrp.repair` module. Two obvious candidates are:
- [x] Greedy repair, as tracked in #182.
- [x] A method based on our local search. Such a method should be possible if we can somehow get our local search to insert required customers into the solution. This came up in #301.

We could at some point also add a `pyvrp.destroy` for destroy operators. That has less priority to me because the destroy step in my experience is a lot simpler than the repair one, and less performance critical (so there's no real need to integrate it into PyVRP like there is for the more expensive repair operators).

**Comment by leonlan** [comment]
With the new `pyrvrp.repair` module, we can also move `crossover::greedyRepair` to there and call it something like `nearestRouteGreedyRepair`/`nearestGreedyRepair`/`nearestRepair`.

**Comment by N-Wouda** [comment]
I want to try removing `crossover::greedyRepair` in favour of one of the repair methods, yes!

**Comment by N-Wouda** [comment]
@leonlan what other LNS repair methods are commonly used for VRP? I think you know that better than I do. We might be able to implement one or two if they're not too complex.

**Comment by leonlan** [comment]
We could implement a random repair procedure: insert each unplanned client into a random position. That's fairly easy and potentially useful in an ILS.

I think regret-$k$ by [Ropke and Pisinger (2006)](https://pubsonline.informs.org/doi/10.1287/trsc.1050.0135) is also worthwhile to implement. Rather than inserting each client one by one, the procedure aims to find in each iteration the client with the highest regret (difference between insert cost for the best route and insert cost for k-best route). This client is then inserted greedily.

It's a bit more complicated to implement though, because it is rather expensive but it can be made efficient by caching the costs.

Another interesting operator could be a granular greedy repair operator. Haven't seen that one before!

**Comment by N-Wouda** [comment]
Revisiting this, I don't really need a method based on LS per se, since it's pretty easy to build such a thing on top of it by users. We already provide all the building blocks for them to do so. We have a few operators once #386 is in, and have made the LS very capable for use in LNS. So I think we're pretty much done here (for now).

All that might need to be done still is $k$-regret, if we want to.

**Comment by N-Wouda** [comment]
A better interface might be `List[Route] -> List[Route]`, rather than `Solution -> Solution`. That avoids the issue with empty routes in the `Solution` (#389). A user can then implement their own mapping from/to solutions, which can be quite trivial in the standard case (e.g., `solution.get_routes()` for the from part, and `Solution(data, routes)` for the to part).

**Comment by N-Wouda** [comment]
Oh, I just posted the above comment again in #389. Let's discuss further there. If we can resolve #389, I think this issue may also be closed.

**Comment by N-Wouda** [comment]
Since we're in agreement in #389, I will close this issue.
