### ISSUE TITLE
ProblemData.num_vehicles return incorrect if number of vehicles not defined in instance.vrp 

### ISSUE THREAD

**Issue by SemUijen** [PyVRP/PyVRP#399]
#### Describe the bug

ProblemData.num_vehicles returns the number of clients-1 if  number of Vehicles not defined in INSTANCE.vrp
Take for example X-n449-k29 only has the number of vehicles defined in its name. 
Currently, I solved this by simply adding VEHICLES : X to the file, because I do not use that many different instances.
but there are a lot of VRP instances that do not have this defined(all of Uchoa for example).

This might be more an issue from the .vrp files or VRPlib,
but this issue might otherwise go left unnoticed 

#### Code sample

```python
    instance = vrplib.read_instance(where, instance_format=instance_format)
    num_vehicles: int = instance.get("vehicles", dimension -1)
```

<details>

pyvrp version: 0.6.3

</details>

#### Expected Output

ProblemData.num_vehicles returns the correct number of vehicles for instances OR
Raise  an error that Number of vehicles is not defined

**Comment by N-Wouda** [comment]
> Take for example X-n449-k29 only has the number of vehicles defined in its name.

@leonlan you know better than I do, but the X instances are not constrained right?

**Comment by leonlan** [comment]
X instances are indeed not constrained in the number of vehicles. See [the paper](https://optimization-online.org/wp-content/uploads/2014/10/4597.pdf) (Section 3.3.2) for more details. The K in the name of the instance serves as lower bound.

**Comment by N-Wouda** [comment]
> X instances are indeed not constrained in the number of vehicles. See [the paper](https://optimization-online.org/wp-content/uploads/2014/10/4597.pdf) (Section 3.3.2) for more details. The K in the name of the instance serves as lower bound.

Thanks! That matches what I recalled from somewhere. Returning to the issue,

>ProblemData.num_vehicles returns the number of clients-1 if number of Vehicles not defined in INSTANCE.vrp
Take for example X-n449-k29 only has the number of vehicles defined in its name.
Currently, I solved this by simply adding VEHICLES : X to the file, because I do not use that many different instances.
but there are a lot of VRP instances that do not have this defined(all of Uchoa for example).

The way I understand the `VEHICLES` specification in the VRPLIB format is as a constraint: when set, it determines the maximum number of vehicles available. When it's not set, there is no restriction (and thus we need at least `num_customers` vehicles to allow for the solution with all singleton routes). In that sense I don't think it's an error when the `VEHICLES` specification is not defined: that just means there is no constraint on the actual number of vehicles. If an instance does want to impose such a constraint, the instance should add the specification to enforce it.

Summarising, the current behaviour seems correct to me. Perhaps we can update the documentation to better explain what happens when `VEHICLES` is not set? [This](https://pyvrp.org/dev/supported_vrplib_fields.html#term-VEHICLES) could do with some more words to explain that in that case we assume the fleet size is not constrained, and set the number of vehicles equal to the number of clients.

**Comment by N-Wouda** [comment]
@SemUijen what do you think?

**Comment by SemUijen** [comment]
@N-Wouda Sorry for the late reply. I think updating the documentation should indeed be enough.
If it is clear that it is set to the number of clients because there is no limitation, that would work.

On the other hand, I am using the lower limit currently as an input for my model, which I currently have to manually add.

But with the purpose of `VEHICLES` being a constraint, not a lower bound,  the current  behavior makes a lot of sense

**Comment by N-Wouda** [comment]
@SemUijen thanks for your reply! I've just updated the docs to better explain what PyVRP does when the `VEHICLES` specification is not provided. I think that closes this issue!
