### ISSUE TITLE
TimeWarp for MaxDuration should consider existing time warp.

### ISSUE THREAD

**Issue by wouterkool** [PyVRP/PyVRP#459]
We currently add time warp when `TimeWindowSegment.duration` exceeds `VehicleType.max_duration` with the idea that we travel back in time to satisfy the `max_duration`. However, the current implementation ignores the fact that the route/`TimeWindowSegment` may already include sufficient time warp to satisfy the `max_duration`. For feasible solutions, there is no difference, but for infeasible solutions, this may result in duplicated time warp which is a bit suprising. My proposal is to only add time warp to satisfy the max_duration constraint if `duration - time_warp` (in `TimeWindowSegment`) exceeds the `max_duration`.

For example: a route has a duration (travel + wait + service) of 3.5h and a timewarp of 0.5h. If the route starts at 12:00, it dus ends at 13:00 + 3h - 0.5h = 15:00. If the `max_duration` is 3h, currently we add another 0.5h of timewarp since 3.5.h > 3h, but I think we should consider the 'net duration' (difference between start and end time including the timewarp), which is already 3h and not add any extra time warp.

Again, as soon as the solution is feasible results are the same, so there is not really a problem, but logically the interpretation of the timewarp for infeasible routes would improve by changing this (which is useful for plotting, debugging of infeasible solutions).

**Comment by leonlan** [comment]
I don't really see an issue with penalizing the time warp twice, but I'm also not opposed to changing it. It's a grey/undefined area and both ways make sense to me. 

Anyway, I think the proposed change might not be that straightforward. Looking at the time warp computation:

https://github.com/PyVRP/PyVRP/blob/3787ae16f96ffa5838969c388fe0b8a9fc7259f3/pyvrp/cpp/TimeWindowSegment.h#L167-L174

Subtracting timewarp from duration like this:

```cpp
          + std::max<Duration>(duration_ - timewarp_ - maxDuration, 0); 
```

is incorrect (I think) because `timewarp_` also includes time warp due to release times, resulting in inconsistency in that definition. One way of doing this is by going back to `timeWarp` and `totalTimeWarp`. But if we have to go into that direction, I think it's just better to stick to the current definition.

**Comment by N-Wouda** [comment]
We discussed this a bit this morning. What's also relevant, and helped me understand everything a bit better, is [this comment in an old PR](https://github.com/PyVRP/PyVRP/pull/241#discussion_r1272707408).

**Comment by N-Wouda** [comment]
I'm moving this to 0.9.0 because I don't want this to block a release of 0.8.0.

**Comment by N-Wouda** [comment]
@wouterkool is this something you want to complete before 0.9.0? (in, say, the coming week or two).

**Comment by wouterkool** [comment]
It's a small change so let's try; I've opened #613. Note this probably conflicts with #586 but that should be easy to resolve.
