### ISSUE TITLE
Release time and edge durations result in time warp and infeasible solutions

### ISSUE THREAD

**Issue by Stanpol** [PyVRP/PyVRP#461]
#### Describe the bug

Setting `release time` for clients or `duration` for edges results in routes having `has_time_warp()==True` and infeasible solutions.

#### Code sample
This is a working example. Take 1000 random clients, all have their release time at 0 and edge durations at 0.
```python
import numpy as np
from pyvrp import Model
from pyvrp.stop import MaxRuntime
from pyvrp.plotting import plot_solution

np.random.seed(0)

n = 1000
x = (np.random.rand(n) * 1000).astype(int)
y = (np.random.rand(n) * 1000).astype(int)
demand = [0] + [1]*999

m = Model()
m.add_vehicle_type(16, capacity=75)
depot = m.add_depot(x=x[0], y=y[0])
clients = [
    m.add_client(x=x[idx], y=y[idx], demand=demand[idx], release_time=0) # release time is 0
    for idx in range(1, len(x))
]

locations = [depot, *clients]
for frm in locations:
    for to in locations:
        duration = distance = abs(frm.x - to.x) + abs(frm.y - to.y)  # Manhattan
        m.add_edge(frm, to, distance=distance, duration=0) # duration is 0

res = m.solve(stop=MaxRuntime(1))  # one second
print(res)
plot_solution(res.best, m.data())
for id, r in enumerate(res.best.get_routes()):
    print(f"Route {id}: Release time {r.release_time()}, "
          f"distance {r.distance()}, "
          f"duration {r.duration()}, "
          f"end time {r.end_time()}, "
          f"vehicle type {r.vehicle_type()}, "
          f"has excess load {r.has_excess_load()}, "
          f"has time warp {r.has_time_warp()}.")
```
A feasible solution was found in 1 second, all the distances are below 5000:
![image](https://github.com/PyVRP/PyVRP/assets/708533/09f68dcc-81c4-4063-9b5f-c71cda0717af)

Let's modify the code. First set the duration equal to distance. And give it a minute to solve.
```python
import numpy as np
from pyvrp import Model
from pyvrp.stop import MaxRuntime
from pyvrp.plotting import plot_solution

np.random.seed(0)

n = 1000
x = (np.random.rand(n) * 1000).astype(int)
y = (np.random.rand(n) * 1000).astype(int)
demand = [0] + [1]*999

m = Model()
m.add_vehicle_type(16, capacity=75)
depot = m.add_depot(x=x[0], y=y[0])
clients = [
    m.add_client(x=x[idx], y=y[idx], demand=demand[idx], release_time=0) # release time is 0
    for idx in range(1, len(x))
]

locations = [depot, *clients]
for frm in locations:
    for to in locations:
        duration = distance = abs(frm.x - to.x) + abs(frm.y - to.y)  # Manhattan
        m.add_edge(frm, to, distance=distance, duration=duration) # duration is equal to distance

res = m.solve(stop=MaxRuntime(60))  # one minute
print(res)
plot_solution(res.best, m.data())
for id, r in enumerate(res.best.get_routes()):
    print(f"Route {id}: Release time {r.release_time()}, "
          f"distance {r.distance()}, "
          f"duration {r.duration()}, "
          f"end time {r.end_time()}, "
          f"vehicle type {r.vehicle_type()}, "
          f"has excess load {r.has_excess_load()}, "
          f"has time warp {r.has_time_warp()}.")
```
It results only with infeasible solutions and each route having a time warp.
![image](https://github.com/PyVRP/PyVRP/assets/708533/570f9171-0b2a-4215-add2-95a9068c4885)

Now let's only add release time: 
```python
import numpy as np
from pyvrp import Model
from pyvrp.stop import MaxRuntime
from pyvrp.plotting import plot_solution

np.random.seed(0)

n = 1000
x = (np.random.rand(n) * 1000).astype(int)
y = (np.random.rand(n) * 1000).astype(int)
demand = [0] + [1]*999

m = Model()
m.add_vehicle_type(16, capacity=75)
depot = m.add_depot(x=x[0], y=y[0])
clients = [
    m.add_client(x=x[idx], y=y[idx], demand=demand[idx], release_time=1) # release time is 1
    for idx in range(1, len(x))
]

locations = [depot, *clients]
for frm in locations:
    for to in locations:
        duration = distance = abs(frm.x - to.x) + abs(frm.y - to.y)  # Manhattan
        m.add_edge(frm, to, distance=distance, duration=0) # duration is 0

res = m.solve(stop=MaxRuntime(60))  # one minute
print(res)
plot_solution(res.best, m.data())
for id, r in enumerate(res.best.get_routes()):
    print(f"Route {id}: Release time {r.release_time()}, "
          f"distance {r.distance()}, "
          f"duration {r.duration()}, "
          f"end time {r.end_time()}, "
          f"vehicle type {r.vehicle_type()}, "
          f"has excess load {r.has_excess_load()}, "
          f"has time warp {r.has_time_warp()}.")
```
Again infeasible solutions and time warp.

Finally, this is the case I'm actually interested in, that I believe can't find any feasible solutions because of the above problems:

```python
import numpy as np
from pyvrp import Model
from pyvrp.stop import MaxRuntime
from pyvrp.plotting import plot_solution

np.random.seed(0)

n = 1000
x = (np.random.rand(n) * 1000).astype(int)
y = (np.random.rand(n) * 1000).astype(int)
demand = [0] + [1]*999

m = Model()
m.add_vehicle_type(8, capacity=75, tw_early=0, tw_late=5000) # vehicles for the first shift
m.add_vehicle_type(8, capacity=75, tw_early=5000, tw_late=100000) # vehicles for the second shift

depot = m.add_depot(x=x[0], y=y[0])
clients_first_shift = [
    m.add_client(x=x[idx], y=y[idx], demand=demand[idx], tw_early=0, tw_late=100000, release_time=0) # release time is 0, can be delivered in both shifts
    for idx in range(1, 500)
]
clients_second_shift = [
    m.add_client(x=x[idx], y=y[idx], demand=demand[idx], tw_early=5000, tw_late=100000, release_time=5000) # release time is 5000
    for idx in range(500, len(x))
]

clients = clients_first_shift + clients_second_shift

locations = [depot, *clients]
for frm in locations:
    for to in locations:
        duration = distance = abs(frm.x - to.x) + abs(frm.y - to.y)  # Manhattan
        m.add_edge(frm, to, distance=distance, duration=duration) # duration is equal to distance

res = m.solve(stop=MaxRuntime(60))  # one minute
print(res)
plot_solution(res.best, m.data())
for id, r in enumerate(res.best.get_routes()):
    print(f"Route {id}: Release time {r.release_time()}, "
          f"distance {r.distance()}, "
          f"duration {r.duration()}, "
          f"end time {r.end_time()}, "
          f"vehicle type {r.vehicle_type()}, "
          f"has excess load {r.has_excess_load()}, "
          f"has time warp {r.has_time_warp()}.")
```
If I solve each shift separately then I can get a feasible solution. However, ideally clients from the first shift can be used in the second shift. I tried to customise penalties for TW and load, but this is not resulting in any feasible solutions.

I'm using the latest version, but this was tested with 0.7.0 as well.
```
INSTALLED VERSIONS
------------------
     pyvrp: 0.8.0a0
     numpy: 1.26.4
matplotlib: 3.8.2
    vrplib: 1.3.0
      tqdm: 4.66.1
     tomli: 2.0.1
    Python: 3.10.12
```

#### Expected Output

Time warp shouldn't happen when there are no constrains broken.

**Comment by N-Wouda** [comment]
Hi @Stanpol! 👋 

Thanks for opening an issue. Let me go through your examples (I'll abbreviate to save some space; hopefully it is clear which code example I'm referring to) and explain what's currently happening:

>First set the duration equal to distance. And give it a minute to solve.

When you specify any duration (as this example does on the edges), suitable time windows must also be provided. All time related components default to zero, but once you specify any time component, you should typically provide all of them. In this case, that means you should provide time windows for the depot and the clients.

>Now let's only add release time:

Same issue: the depot and the clients default to a time window of `[0, 0]`, which can never be met when `release_time = 1`.

>Finally, this is the case I'm actually interested in, that I believe can't find any feasible solutions because of the above problems:

This case _almost_ works, except that there is no time window specified on the depot. So that one defaults to `[0, 0]`. If you were to specify `[0, 100_000]`, this example works.

---

Now, I realise writing this reply that the ergonomics of our current interface are less than ideal. It is easy to miss one or more time-related values, and then the whole thing no longer works. Should we make the fields truly optional? E.g., if you do not provide a time window (maybe using `None` as a default instead of `0`) it is unconstrained for that client or depot? That seems much more intuitive than the current interface.

What do you think?

**Comment by N-Wouda** [comment]
@leonlan @wouterkool: we need to document this better and probably rethink the interface to be much more forgiving when time components are used. I think it can be as simple as making the time windows completely optional, either by marking them `None`, or setting `tw_late` to a large integer. `None` is probably better, to avoid overflow issues that might happen when we use large integer defaults.

**Comment by Stanpol** [comment]
Thanks a lot @N-Wouda for a quick reply. It makes total sense. 

Another option is to provide more information to the users about exactly which constrains are broken. If I see that a route is infeasible because it starts at `release_time=1` and the depot has `tw_latest=0` I can quickly understand that I didn't set the correct time window. 

Currently, all I know is that there is time warp, but is it a client problem or is a depot problem or is a vehicle problem?

**Comment by N-Wouda** [comment]
Part of 'fixing' this is the following:
- #462 adds debug-build asserts to check for integer over- and underflow. This should help determine whether we implemented something without taking into account such issues.
- #463 makes the default time windows `[0, INT_MAX]`, rather than `[0, 0]`. It also adds a few additional checks when creating new clients (e.g., `release_time` cannot be negative, and `release_time` cannot be later than `tw_late`).

@Stanpol this should already help with at least some of the issues you encountered in the examples above.

> Another option is to provide more information to the users about exactly which constrains are broken. If I see that a route is infeasible because it starts at `release_time=1` and the depot has `tw_latest=0` I can quickly understand that I didn't set the correct time window.

A small part of this can already be gathered through the plotting tools, and then particularly [`pyvrp.plotting.plot_route_schedule`](https://pyvrp.org/api/plotting.html#pyvrp.plotting.plot_route_schedule.plot_route_schedule). We should probably add a bit more to the documentation about how to use such tools when dealing with infeasibility.
