### ISSUE TITLE
Switch to int64_t?

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#468]
Our current use of `int32_t` is sufficient for most simple routing problems, but makes it hard to balance multiple different cost aspects in the objective. Suppose, for example, that the distance factors in at a cost of 0.21 euro/km, and the driver's hourly costs amount to some 30 euros. Taking both into account in the objective would amount to a route cost of $(0.21 / 1000) d + (30 / 3600) t $, where $d$ and $t$ are the route's distance and duration in meters and seconds, respectively.

Turning this expression into something integral requires the multiplication by $1000 \cdot 3600$, resulting in an integral objective function of $756 d + 30000 t$. With this objective, the limits of a `int32_t` are such that we cannot have routes longer than about 20h, or 2800km. Either of those maxima seem very easy to reach in practical applications (e.g., long haul).

Switching to a larger integer type would help with this, but we'll need to be careful to check the impact on performance of this change.

**Comment by N-Wouda** [comment]
If we switch to this I think we can also reasonably remove the scaling warnings related to `MAX_USER_VALUE` and `MAX_VALUE` in the `constants.py` file. 64-bit ints are so large that is unlikely to ever be a problem a user might encounter.

**Comment by N-Wouda** [comment]
Additionally, if we go for this we probably no longer need the double precision mode either. Just multiply everything $\times 10^5$ or so, and you'll get the exact same solutions.

Let's hope this is fast :-).

**Comment by N-Wouda** [comment]
Looking at the results above, I am afraid this is probably not worthwhile - the results from doing this are worse than just using double precision. Alas!

**Comment by leonlan** [comment]
I was running VRPB benchmarks for #434. To solve these VRPB instances, we can set some arc weights to `MAX_USER_VALUE` to obtain feasible VRPB solutions, but this led to overflows on large instances (>700 clients). 

One way to avoid these overflows is to use `int64_t` instead of `int32_t`. The earlier posts show that this led to a 25% decrease in iterations. However, this does not lead to much lower gaps: for VRPTW, the gap increases from 0.49% to 0.53%, and for CVRP, the gap increases from 0.23% to 0.24%. For CVRP it surprises me that the number of iterations hardly decreases. I ran the benchmark twice to doublecheck and it had the same result.

These results are convincing enough for me to switch to `int64`. allowing PyVRP to deal with much larger values and avoid overflow issues.

Details below.

<details><summary>CVRP</summary>
<p>

With int32
```
 mean: 63287 (min: 63279, max: 63298)
  gap: 0.23%
iters: 105967
```

With int64
```
 mean: 63289 (min: 63283, max: 63300)
  gap: 0.24%
iters: 102974
```

</p>
</details> 


<details>
<summary>VRPTW</summary>
<p>

With int32
```
 mean: 333187 (min: 333118, max: 333266)
  gap: 0.49%
iters: 98064
```

With int64
```
 mean: 333336 (min: 333225, max: 333438)
  gap: 0.53%
iters: 73107
```

</p>
</details>

**Comment by N-Wouda** [comment]
OK let's just do this then. We can also simplify a bit further from this. Shall I draft a PR? Let's leave double precision in for now. It's pretty easy to continue to support. Do we want to keep the (max) user value? I think we can remove it with this change.

**Comment by leonlan** [comment]
Yea sure let’s remove that too. But we keep MAX_VALUE right for setting arc weights?
