### ISSUE TITLE
Add SPD / backhaul example to the docs

### ISSUE THREAD

**Issue by omganeshdahale** [PyVRP/PyVRP#486]
I'm exploring PyVRP for pickup and delivery problems but couldn't find any example in the docs.
Can you please provide an example for such a scenario? thanks

**Comment by N-Wouda** [comment]
Hi Om, we will probably add such an example to the docs soon-ish, but likely before releasing v0.8.0. Support for (some variants of) pickup and delivery and backhaul was added less than a week ago; it's not completely fleshed out yet. Particularly not in the docs.

**Comment by omganeshdahale** [comment]
Hi Niels, I got it. For now, can you leave a brief example here?
Also, is there a discord server for pyvrp or where we can connect? I would like to learn more about it

**Comment by N-Wouda** [comment]
> For now, can you leave a brief example here?

Sure: first, build PyVRP [from source](https://pyvrp.org/setup/installation.html#installing-from-source) because support for simultaneous pickup and delivery is not yet on PyPI. Then, every client object now has a `delivery` and `pickup` attribute: delivery is an amount that goes from the depot to the client (linehaul), and pickup is an amount to goes from the client back to the depot (backhaul).

Thus, something like this will work:
```python
from pyvrp import Model

m = Model()
client = m.add_client(x=0, y=0, delivery=5, pickup=10)
# etc.
```

>Also, is there a discord server for pyvrp or where we can connect?

Not currently, but I'll discuss this with @leonlan and @wouterkool!

**Comment by omganeshdahale** [comment]
How can I pickup from one client and deliver it to another?

**Comment by N-Wouda** [comment]
> How can I pickup from one client and deliver it to another?

You cannot, that problem variant is not yet supported. Feel free to provide a patch if this is something you need quickly. I'll happily review a PR for one-to-one pickup and delivery!

**Comment by omganeshdahale** [comment]
Sure, please update on the discord part as well, you can share your username too if possible

**Comment by N-Wouda** [comment]
> Sure, please update on the discord part as well, you can share your username too if possible

I do not have Discord. @leonlan and I have discussed setting something like that up, but we're both somewhat disinclined to do this for now due to the additional workload that would entail. The issue tracker here on GitHub will have to suffice for the forseeable future!

**Comment by omganeshdahale** [comment]
Okay no issues
