### ISSUE TITLE
Retrieve Client Visit Times

### ISSUE THREAD

**Issue by NUllmann99** [PyVRP/PyVRP#715]
#### Is your feature request related to a problem? 
I am solving a capacitated VRP with time windows and would like to efficiently retrieve the time when a customer is visited. This would include the time when the vehicle arrives and leaves.

#### Describe the solution you'd like
A function like solution.client_information(), which would display the solution's client visit information in a e.g. format:
Route | Client | Start_visit | End_visit

#### Describe alternatives you have considered
Currently, I'm trying to retrieve this information through the plot_route_schedule() function, which is hard to read when multiple points are in a route and tiresome as you have to check the order in which points are visited.

#### Additional context
-

**Comment by N-Wouda** [comment]
Hi @NUllmann99, thanks for your suggestion - I think this'll be a useful addition. These statistics are probably also useful to other users (and have come up before, e.g. in #673). I'll need to think a bit about how to add this - it'll probably be something like a list of data objects that can be retrieved per route (for example `route.schedule()`), rather than a report like your proposed `solution.client_information()` method.

**Comment by alessio-locatelli** [comment]
I was scrolling through all issues and this one is the most relevant. I came across a similar problem when it is hard to map back the solution result to the real world. To add more context: Imagine there are multiple trains and buses between cities "A" and "B" with different prices and durations. I am creating a PyVRP model with multiple edges. Once I get a solution, all I have is a list of visited node IDs that I map back to the real cities. Unfortunately, I see no clear way to see the selected edges so I can map them to the real trains and buses. Am I misunderstanding something or is this unsupported?

Another example. Imagine there are two flights: one is faster and another is cheaper. I am creating two edges, but, again, all I get from the solution is a list of visited nodes. 

Exporting `Statistics` does not have that information too.

**Comment by N-Wouda** [comment]
@alessio-locatelli after solving, the result contains a solution (`res.best`). That solution tracks routes (`res.best.routes()`), each of which expose the vehicle type index associated with the route (for each `route` as `route.vehicle_type()`). The associated vehicle type can be obtained from either the data instance (as `data.vehicle_type(route.vehicle_type())`), or the model as `m.vehicle_types[route.vehicle_type()]`.

I do not understand what you mean by "all I get from the solution is a list of visited nodes" since there's much more available than just that.
